# Generated by Django 5.0.6 on 2024-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('perhour', models.CharField(max_length=50)),
            ],
        ),
    ]
